[project]
name = "salaah-mcp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi-mcp>=0.3.4",
    "fastapi[standard]>=0.115.12",
    "islamic-times>=2.0.7",
]
