version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "salaah-mcp"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket"
s3_prefix = "salaah-mcp"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = false
image_repositories = []
