AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Salaah MCP - Islamic Prayer Times API

Globals:
  Function:
    Timeout: 30
    MemorySize: 256
    Runtime: python3.12
    Architectures:
      - x86_64

Resources:
  SalaahMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: app.main.handler
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          STAGE: prod

Outputs:
  SalaahMCPApi:
    Description: API Gateway endpoint URL for Salaah MCP
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
  SalaahMCPFunction:
    Description: Lambda Function ARN
    Value: !GetAtt SalaahMCPFunction.Arn
