AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Salaah MCP - Islamic Prayer Times API (Cost Optimized)

Globals:
  Function:
    Timeout: 15
    MemorySize: 128
    Runtime: python3.12
    Architectures:
      - x86_64
    LoggingConfig:
      LogGroup:
        LogGroupName: !Sub "/aws/lambda/${AWS::StackName}"
        RetentionInDays: 7

Resources:
  SalaahMCPFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../
      Handler: app.main.handler
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
      Environment:
        Variables:
          STAGE: prod

Outputs:
  SalaahMCPApi:
    Description: API Gateway endpoint URL for Salaah MCP
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
  SalaahMCPFunction:
    Description: Lambda Function ARN
    Value: !GetAtt SalaahMCPFunction.Arn
